version: '3.8'

services:
  database-mc:  # Set a custom container name for the database
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mc_microservice
    ports:
      - "3309:3306"
    volumes:
      - mysql-data-user:/var/lib/mysql

  application-mc:  # Set a custom container name for the service
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - database-mc
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-mc:3306/mc_microservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  mysql-data-user:
