version: '3.8'

services:
  database-userservice:  # Set a custom container name for the database
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: new_user
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-user:/var/lib/mysql

  application-userservice:  # Set a custom container name for the service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database-userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-userservice:3306/new_user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  mysql-data-user:
